# Generated by Django 5.0.3 on 2024-04-06 09:44

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_url', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('discription', models.TextField(blank=True)),
                ('category_image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product_url', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('price', models.FloatField()),
                ('actual_price', models.FloatField(blank=True)),
                ('dicription', models.TextField(blank=True)),
                ('delivery', models.IntegerField()),
                ('availability', models.CharField(choices=[('In Stock', 'in_stock'), ('Limited', 'limited'), ('On Order', 'on_order'), ('Out of Stock', 'out_of_stock')], max_length=20)),
                ('product_image', models.ImageField(upload_to='product')),
                ('product_image_2', models.ImageField(blank=True, upload_to='product')),
                ('product_image_3', models.ImageField(blank=True, upload_to='product')),
                ('product_image_4', models.ImageField(blank=True, upload_to='product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
