# Generated by Django 5.0.4 on 2024-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('site_title', models.CharField(blank=True, max_length=100)),
                ('site_discription', models.CharField(blank=True, max_length=300)),
                ('site_logo', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
