# Generated by Django 5.0.2 on 2024-04-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='url',
        ),
    ]
