# Generated by Django 5.0.2 on 2024-04-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_slug_category_url_rename_slug_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='category_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='product_url',
        ),
    ]
